<?php $images = $this->getPicture($this->model,1,$this->gift['product_id'],"medium"); 
?>
<div class="slider-wrapper theme-pascal">
    <div class="ribbon"></div>
    <div id="slider" class="nivoSlider">
    	<?php foreach ($images['pictures'] as $image):?>
        <img src="<?php echo $image?>" alt="" />
        <?php endforeach;?>
    </div>
    <div id="htmlcaption" class="nivo-html-caption">
        <strong>This</strong> is an example of a <em>HTML</em> caption with <a href="#">a link</a>.
    </div>
</div>
<script type="text/javascript">
$(window).load(function() {
    $('#slider').nivoSlider();
});
</script>