<div class="panel-divider"></div>
<div id="seans-result">
	Tebrikler !!!
</div>
<span class="result win"></span>
<div id="result-detail">
Tebrikler <?php echo isset($this->last_count) ? $this->last_count. ". tıklayarak ": ''?>  hediyeyi kaptınız.<br/> <a style="color: #33CCFF" href='/bana-ozel'>Bana Özel</a> sayfasının kazandıklarım başlığından bilgi alabilirsiniz.
<br/><?php echo isset($this->is_awarded) ? $this->is_awarded: "";?>
</div>