<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'>
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
	<meta http-equiv='Content-Type' content='text/html; charset=UTF-8' />
	<?php echo $this->headTitle()?>
		<link href='/assets/css/style.css' type='text/css' rel='stylesheet' />
		<script language='javascript' type='text/javascript' src='/assets/scripts/jquery.js'></script>

<script language="javascript">

</script>
</head>
<body>
<div id="header-container">
	<div class="wrapper">
		<div id="header">
			<div id="logo">
			</div>
			<div id="login-buttons">
				<span>
					<a id="to-login" class="login-button">Giriş</a>
					<a href="/sign-up" class="login-button">Üye Ol</a>
				</span>
			</div>
		</div>
	</div>
</div>
<div id="nav-container">
	<div class="wrapper">
		<div id="nav">
			<a href="#">ŞİMDİKİ HEDİYE</a>
			<span class="anchor-divider"></span>  
			<a href="#">KAÇAN HEDİYELER</a>
			<span class="anchor-divider"></span>
			
			<a href="#">NASIL ÇALIŞIR?</a>
			<span class="anchor-divider"></span>
			<a href="#">FİRMALARA ÖZEL</a>
			<span class="anchor-divider"></span>
			<a href="#">BANA ÖZEL</a>
			
		</div>
	</div>
</div>
<div id="content-container">
	<div class="wrapper">
		<div id="content">
		<div id="sub-nav">
				<?php echo $this->sidebar?>
			</div>
<?php echo $this->layout()->content?>
		</div>
	</div>	
</div>
<div id="footer-container">
	<div class="wrapper">
		<div id="footer">
		
		</div>
	</div>	
</div>
</body>
</html>