<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'>
<html xmlns='http://www.w3.org/1999/xhtml'>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8' />
<link href='/assets/css/style.css' type='text/css' rel='stylesheet' />
<link href='/assets/css/login.css' type='text/css' rel='stylesheet' />

</head>
<body>
<div id='container'>
<div id='login-panel'>
<div id='login'>
<form method='post'>
<?php echo $this->flashMessage()?>
<p><label for='username'>Kullanıcı Adı</label> <input type='text'
	name='username' class="login" /></p>
<p><label for='password'>Şifre</label> <input type='password'
	name='password' class='login' /></p>
<p><input type='submit' value='Giriş' id='user_session_submit' /></p>
</form>
</div>
</div>
</div>

</body>

</html>
